config/routes.rb
Rails.application.routes.draw do
  resources :listatareas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listatarea.rb
class Listatarea < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listatareas_controller.rb
class ListatareasController < ApplicationController
  before_action :set_listatarea, only: [:show, :edit, :update, :destroy]

  # GET /listatareas
  # GET /listatareas.json
  def index
    @listatareas = Listatarea.all
  end

  # GET /listatareas/1
  # GET /listatareas/1.json
  def show
  end

  # GET /listatareas/new
  def new
    @listatarea = Listatarea.new
  end

  # GET /listatareas/1/edit
  def edit
  end

  # POST /listatareas
  # POST /listatareas.json
  def create
    @listatarea = Listatarea.new(listatarea_params)

    respond_to do |format|
      if @listatarea.save
        format.html { redirect_to @listatarea, notice: 'Listatarea was successfully created.' }
        format.json { render :show, status: :created, location: @listatarea }
      else
        format.html { render :new }
        format.json { render json: @listatarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listatareas/1
  # PATCH/PUT /listatareas/1.json
  def update
    respond_to do |format|
      if @listatarea.update(listatarea_params)
        format.html { redirect_to @listatarea, notice: 'Listatarea was successfully updated.' }
        format.json { render :show, status: :ok, location: @listatarea }
      else
        format.html { render :edit }
        format.json { render json: @listatarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listatareas/1
  # DELETE /listatareas/1.json
  def destroy
    @listatarea.destroy
    respond_to do |format|
      format.html { redirect_to listatareas_url, notice: 'Listatarea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listatarea
      @listatarea = Listatarea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listatarea_params
      params.require(:listatarea).permit(:nombre, :desde, :hasta, :responsable, :realizado, :observacion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listatareas_helper.rb
module ListatareasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PabloFinal3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listatareas/_form.html.erb
<%= form_with(model: listatarea, local: true) do |form| %>
  <% if listatarea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listatarea.errors.count, "error") %> prohibited this listatarea from being saved:</h2>

      <ul>
      <% listatarea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :desde %>
    <%= form.date_select :desde %>
  </div>

  <div class="field">
    <%= form.label :hasta %>
    <%= form.date_select :hasta %>
  </div>

  <div class="field">
    <%= form.label :responsable %>
    <%= form.text_field :responsable %>
  </div>

  <div class="field">
    <%= form.label :realizado %>
    <%= form.check_box :realizado %>
  </div>

  <div class="field">
    <%= form.label :observacion %>
    <%= form.text_field :observacion %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listatareas/edit.html.erb
<h1>Editing Listatarea</h1>

<%= render 'form', listatarea: @listatarea %>

<%= link_to 'Ver', @listatarea %> |
<%= link_to 'Volver', listatareas_path %>

app/views/listatareas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de tareas de Pablo V</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Desde</th>
      <th>Hasta</th>
      <th>Responsable</th>
      <th>Realizado</th>
      <th>Observación</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listatareas.each do |listatarea| %>
      <% if listatarea.realizado == false %>
        <tr>
          <td><%= listatarea.nombre %></td>
          <td><%= listatarea.desde %></td>
          <td><%= listatarea.hasta %></td>
          <td><%= listatarea.responsable %></td>
          <td><%= listatarea.realizado %></td>
          <td><%= listatarea.observacion %></td>
          <td><%= link_to 'Ver', listatarea %></td>
          <td><%= link_to 'Editar', edit_listatarea_path(listatarea) %></td>
          <td><%= link_to 'Eliminar', listatarea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva tarea', new_listatarea_path %>

app/views/listatareas/new.html.erb
<h1>New Listatarea</h1>

<%= render 'form', listatarea: @listatarea %>

<%= link_to 'Volver', listatareas_path %>

app/views/listatareas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @listatarea.nombre %>
</p>

<p>
  <strong>Desde:</strong>
  <%= @listatarea.desde %>
</p>

<p>
  <strong>Hasta:</strong>
  <%= @listatarea.hasta %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @listatarea.responsable %>
</p>

<p>
  <strong>Realizado:</strong>
  <%= @listatarea.realizado %>
</p>

<p>
  <strong>Observacion:</strong>
  <%= @listatarea.observacion %>
</p>

<%= link_to 'Editar', edit_listatarea_path(@listatarea) %> |
<%= link_to 'Volver', listatareas_path %>